version: '3.8'

services:
  dechecker-backend:
    build: model_data
    container_name: dechecker_api
#    ports:
#      - "8000:8000"
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - PYTHONDONTWRITEBYTECODE=1
    # Добавляем команду с флагом --reload для автоперезапуска Python-кода
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      # 1. Монтируем код приложения (изменения в app.py применятся мгновенно)
      - .:/app
      # 2. Оставляем монтирование папки с моделями, чтобы они не стирались
      - ./model_data:/app/models
    restart: unless-stopped